apiVersion: apps/v1
kind: Deployment
metadata:
  name: bully-app
spec:
  selector:
    matchLabels:
      app: bully-app
  replicas: 2
  template:
    metadata:
      name: bully-app
      labels:
        name: bully-app
        app: bully-app
        leader: "False"
    spec:
      serviceAccountName: label-sa # Using custom SA
      containers:
        - name: bully-container
          image: bully-app
          imagePullPolicy: Never # Use local image inside Minikube
          env:
            - name: WEB_PORT
              value: "8080"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME # Added env. var.
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

          ports:
            - containerPort: 8080
              name: http
              protocol: TCP